# Generated by Django 4.0 on 2024-01-06 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1, null=True), size=None)),
                ('puts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1, null=True), size=None)),
                ('final', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1, null=True), size=None)),
            ],
        ),
    ]
